### ISSUE TITLE
test.py 的bug 以及 UCF的AUC结果不一致

### ISSUE THREAD

**Issue by yft1996** [fjchange/MIST_VAD#11]
你好，感谢你的开源工作。
我在运行你的代码时遇到了一些问题，想咨询一下：
1.def eval_UCF(args,model,test_dataloader): 中
调用`eval(total_scores, total_labels）`的参数与定义的参数不一致。
将其改为`eval(total_scores, total_labels, n_scores)`后，经debug发现 n_scores为空列表
请问正确调用是什么样的
2.我从UCF数据集中找出了Temporal_Anomaly_Annotation_New.txt文件中所记录的视频放到了一个文件夹内。执行make_h5.py将这些视频转化为了一个H5文件，我在 OneDrive上下载你所提供的所有文件并修改了constant.py文件。
执行 `python test.py --gpus 0 --MODEL UCF_C3D` 得到的结果 为`AUC 59.73%, GAP 10.07%`
执行 `python test.py --gpus 0 --MODEL UCF_I3D` 得到的结果 为`AUC 62.59%, GAP 7.95%`
这与Tabel 的 结果相差太大了， 请问你用的UCF中哪些视频测试的结果？
3.论文里 自引导注意力编码器中 F1 和 F3 输出了的 2k 通道的特征图，k是指什么我不太明白，以及最后的输出结果只给出了异常得分，我看demo里还有异常类别。那么MIST的输出是仅输出片段级的每帧得分 还是既有得分又有异常类别呢？

**Comment by fjchange** [comment]
1. 我已经修改了下该处代码
2. 请查看issue#6， 我没有做任何改动，基于上次测试，上传的模型是能够有论文中的表现，并被#6复现
3. k实际上类似于multi head classification. 这里只是做异常分数预测，并没有分类，demo只是为了方便查看标上了视频中异常的类别。

**Comment by yft1996** [comment]
1.大概是因为我用的是python3.6版本较低，list需要转为np数组才能实现逐像素相减
将 cal_false_alarm函数内的

```python
fp=np.sum(scores*(1-labels))
return fp/np.sum(1-labels)
```
改为

```python
fp=np.sum(scores*(1-np.array(labels)))
return fp/np.sum(1-np.array(labels))
```
可以解决 TypeError: unsupported operand type(s) for -: 'int' and 'list' 的bug 


2.在生成h5文件时，由于我将UCF的测试视频放置到了一个文件内。而make_h5.py生成h5文件时，对于含有字符串Normal的视频会在路径内额外添加一个Normal/目录，导致正常的视频没有添加到h5文件中。
这就导致我之前测试时，评价时仅计算了测试集中异常视频的得分缺失了正常视频的得分。
修改后生成了35.2G的h5文件，评价结果与论文Table1一致：
UCF_C3D: AUC 81.43%, FAR 2.19%, GAP 30.50%
UCF_I3D: AUC 82.30%, FAR 0.13%, GAP 17.71%

感谢你的回复，问题已经解决
