### ISSUE TITLE
About the visualization

### ISSUE THREAD

**Issue by shyern** [fjchange/MIST_VAD#12]
When I test on the UCF-Crime dataset using `python test.py --gpus 0,1,2,3 --MODEL UCF_C3D --vis_UCF`, 
`FileNotFoundError: [Errno 2] No such file or directory: 'data/Test_Spatial_Annotation.npy'`
I cannot find this file, could you provide this file?

**Comment by fjchange** [comment]
I have uploaded these files in the `data/` dir.
