### ISSUE TITLE
About the hyperparameter T in training stage 1

### ISSUE THREAD

**Issue by shyern** [fjchange/MIST_VAD#17]
In the paper, "We uniformly sample L subsets from these video clips, and each subset contains T consecutive clips, forming L sub-bags"
In section 4.2, "Here, We adopt hyperparameters L = 32, T = 3, ".
But in "stage1training/train_MIL_Generator.py" of the released code, the "--part_len" is set to 7 as default for shanghaitech dataset.
How to set the hyperparameter T?

Thanks for your great work. 
Looking forward to your reply.

**Comment by fjchange** [comment]
L=32 for all the datasets and models. T=3 for UCF_C3D, T=4 for UCF_I3D, T=7 for Shanghaitech.
