### ISSUE TITLE
about train_MIL_Generator

### ISSUE THREAD

**Issue by Belize9709** [fjchange/MIST_VAD#18]
I have downloaded your onedrive, including all the files of Baidu cloud and the Shanghai tech dataset.
Following your tutorial, I updated constant after downloading all weights. Then no new files were found in the folder.
Then I directly opened train in the first training stage, stage1 training_ MIL_ Generator.
In model_ path_ Pre and model_ Path and pseudo_ Labels_ The corresponding file cannot be found in dir.
Thank you for your excellent work.
We look forward to your reply.

**Comment by fjchange** [comment]
All these paths you mentioned are set to store trained checkpoints or generated pseudo labels. Thus, you can set the path as you want.
