### ISSUE TITLE
About UCF_I3D_train.py & UCF_C3D_train.py for stage2training 

### ISSUE THREAD

**Issue by Jerry-muyangren** [fjchange/MIST_VAD#19]
1) The code in UCF_C3D_train.py in the stage2training folder is the same as UCF_C3D_options.py in the configs folder. I doubt you are making a mistake?

2) The description of "## 5. Stage 2 training" in Training_Guideline.md says：
*************************
% for UCF_I3D
bash UCF_I3D_train.sh
*************************
However, there is no UCF_I3D_train.sh and UCF_I3D_train.py in the stage2training folder.

Looking forward to your reply。

Thanks !

**Comment by Jerry-muyangren** [comment]
@fjchange please!

**Comment by fjchange** [comment]
1. Thanks. It's a mistake and has been fixed.
2. Sorry, no plan to release this part.
