### ISSUE TITLE
pre-training model file

### ISSUE THREAD

**Issue by xubiao-ui** [fjchange/MIST_VAD#22]
Hello, please tell me how to generate the pre-training model file in MIST, because I want to run your algorithm with my own data set.

**Comment by fjchange** [comment]
Pretrained models, i.e., kinetics pretrained I3D model and Sport1M pretrained C3D model, have been uploaded in the  [OneDrive](https://1drv.ms/f/s!Ai48CHyipiNUkFTHTQGze7QLY1Fn). If you want the ShanghaiTech and UCF-Crime trained models, they are uploaded in [OneDrive](https://1drv.ms/f/s!Ai48CHyipiNUkFTHTQGze7QLY1Fn)  too.
