### ISSUE TITLE
MIL.pth

### ISSUE THREAD

**Issue by Jerry-muyangren** [fjchange/MIST_VAD#24]
在stage1training/train_MIL_Generator.py中的，
第136行：    parser.add_argument('--model_path',type=str,default='/jiachang/Weakly_Supervised_VAD/Datasets/MIL.pth')
请问里面的MIL.pth是什么文件呢？

**Comment by Jerry-muyangren** [comment]
已经解决

**Comment by Belize9709** [comment]
> 已经解决

请问怎么解决的？

**Comment by Smallwhite999** [comment]
> 已经解决



> 在stage1training/train_MIL_Generator.py中的， 第136行： parser.add_argument('--model_path',type=str,default='/jiachang/Weakly_Supervised_VAD/Datasets/MIL.pth') 请问里面的MIL.pth是什么文件呢？

这个.pth文件是要在第一步中生成还是在read.me中的连接下载啊？但是我看里面没有，这个怎么解决啊？谢谢
