### ISSUE TITLE
test.py  bug "cal_false_alarm" ：eval_utils.py:40: RuntimeWarning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by Jerry-muyangren** [fjchange/MIST_VAD#26]
你好，感谢你的开源工作。我的版本：python3.6.7。

我在运行你的test.py代码时，计算 FAR 遇到了一些问题，报错如下：
../utils/eval_utils.py:40: RuntimeWarning: invalid value encountered in double_scalars
发现，是eval_utils.py中：
`fp=np.sum(scores*(1-labels))
return fp/np.sum(1-labels)`的问题。

尝试将这两行修改为：
`fp=np.sum(scores*(1-np.array(labels)))
return fp/np.sum(1-np.array(labels))`
但是没有效果，依然报同样的错。

而且已将test.py中的：
` far=cal_false_alarm(normal_scores,[0]*len(normal_scores))`
修改为：
` far=cal_false_alarm(normal_scores,np.zeros(len(normal_scores),dtype=int))`
还是报同样的错

**Comment by fjchange** [comment]
It may be a problem caused by your numpy version.

**Comment by borijang** [comment]
I've had this problem, it most likely isn't the numpy version. My h5 file did not include the normal videos (wrong normal videos path in make_h5.py, the script didn't raise any errors), it only had the anomaly ones. Including the normal videos fixed this issue.
