### ISSUE TITLE
about the problem of AUC reduction after enabling multi-process

### ISSUE THREAD

**Issue by wwrdi** [fjchange/MIST_VAD#28]
hello:
         I encountered this problem while reproducing your work  ,when set num_wokers =0 ,AUC close to the accuracy of the paper.but ,set to not 0,AUC decreased by four percentage .Have you encountered this problem?
        Looking forward to your reply.

**Comment by fjchange** [comment]
Sorry, I haven't met this problem. I use num_workers=4 for all the stage 2 training.
