### ISSUE TITLE
第一阶段训练生成不了AUC大于0.9的伪劣标生成器

### ISSUE THREAD

**Issue by fmandune** [fjchange/MIST_VAD#29]
最好的模型也是0.877是什么问题

**Comment by fmandune** [comment]
而且伪劣标与实际标签相差还挺大的

**Comment by fmandune** [comment]
你好请问是我伪劣标生成的方式有误吗

**Comment by FiresWorker** [comment]
===================
AUC      0.835391494855726
FAR     0.0062083220180441144
Gap     0.19289014930875312     RMSE    0.22077137759782064
best_AUC 0.8796058476775594 at epoch 2380
===================
同样遇到了这个问题。

训练过程中用到几个参数：
feature_rgb_path: SHT_I3D_RGB.h5,
part_len: 7 (这个应该是文章中的T，文章里给的参数T=3)

提供了这样一个预训练好的模型：SHT_I3D_AUC_0.9483.pth，他可以达到0.94.
可能试着改变一下参数，看能不能达到这个效果。

**Comment by FiresWorker** [comment]
看了一下其他的问题，在一个里面作者给出了关于part_len的回答：
L=32 for all the datasets and models. T=3 for UCF_C3D, T=4 for UCF_I3D, T=7 for Shanghaitech.

**Comment by chiao666** [comment]
> 看了一下其他的问题，在一个里面作者给出了关于part_len的回答： L=32 for all the datasets and models. T=3 for UCF_C3D, T=4 for UCF_I3D, T=7 for Shanghaitech.

我也碰见了这个问题，但是我使用的就是上海科技大学的数据集，按照他默认的配置，也训练不出大于0.9的模型，不知道老哥这里调整了哪些参数，训练出来了吗

**Comment by FiresWorker** [comment]
额，到现在为止并没有得到大于0.9的结果。
然后之前以为SHT_I3D_AUC_0.9483.pth这个模型是阶段一的结果，但发现这个是最后阶段2的模型，所以0.94也就没有参考意义。

我比较过我的0.879得到的伪标签和他的感觉差距还是挺大的。但是我还没有进行阶段2的训练，所以还不清楚这两个伪标签的差距。你有用自己训练的伪标签进行阶段2的训练么，结果如何？

你的意思是你没有用他提供的这个处理过的特征集 ”SHT_I3D_RGB.h5“，是自己用上海科技的数据用I3D训练得到特征再进行阶段1的训练的么？

参数吗，阶段1涉及的参数很少呀，感觉就四个吧，part_num,part_len,这两个涉及采样方法，topk，lambda_1这两个涉及loss。

最近还有其他事，不是很有时间一直复现这个结果，之后要是有了进展，在交流。

**Comment by FiresWorker** [comment]
> > 看了一下其他的问题，在一个里面作者给出了关于part_len的回答： L=32 for all the datasets and models. T=3 for UCF_C3D, T=4 for UCF_I3D, T=7 for Shanghaitech.
> 
> 我也碰见了这个问题，但是我使用的就是上海科技大学的数据集，按照他默认的配置，也训练不出大于0.9的模型，不知道老哥这里调整了哪些参数，训练出来了吗

额，到现在为止并没有得到大于0.9的结果。
然后之前以为SHT_I3D_AUC_0.9483.pth这个模型是阶段一的结果，但发现这个是最后阶段2的模型，所以0.94也就没有参考意义。

我比较过我的0.879得到的伪标签和他的感觉差距还是挺大的。但是我还没有进行阶段2的训练，所以还不清楚这两个伪标签的差距。你有用自己训练的伪标签进行阶段2的训练么，结果如何？

你的意思是你没有用他提供的这个处理过的特征集 ”SHT_I3D_RGB.h5“，是自己用上海科技的数据用I3D训练得到特征再进行阶段1的训练的么？

参数吗，阶段1涉及的参数很少呀，感觉就四个吧，part_num,part_len,这两个涉及采样方法，topk，lambda_1这两个涉及loss。

最近还有其他事，不是很有时间一直复现这个结果，之后要是有了进展，在交流。

**Comment by chiao666** [comment]
> > > 看了一下其他的问题，在一个里面作者给出了关于part_len的回答： L=32 for all the datasets and models. T=3 for UCF_C3D, T=4 for UCF_I3D, T=7 for Shanghaitech.
> > 
> > 
> > 我也碰见了这个问题，但是我使用的就是上海科技大学的数据集，按照他默认的配置，也训练不出大于0.9的模型，不知道老哥这里调整了哪些参数，训练出来了吗
> 
> 额，到现在为止并没有得到大于0.9的结果。 然后之前以为SHT_I3D_AUC_0.9483.pth这个模型是阶段一的结果，但发现这个是最后阶段2的模型，所以0.94也就没有参考意义。
> 
> 我比较过我的0.879得到的伪标签和他的感觉差距还是挺大的。但是我还没有进行阶段2的训练，所以还不清楚这两个伪标签的差距。你有用自己训练的伪标签进行阶段2的训练么，结果如何？
> 
> 你的意思是你没有用他提供的这个处理过的特征集 ”SHT_I3D_RGB.h5“，是自己用上海科技的数据用I3D训练得到特征再进行阶段1的训练的么？
> 
> 参数吗，阶段1涉及的参数很少呀，感觉就四个吧，part_num,part_len,这两个涉及采样方法，topk，lambda_1这两个涉及loss。
> 
> 最近还有其他事，不是很有时间一直复现这个结果，之后要是有了进展，在交流。

我复现出来的差不多也是0.87，正准备按照这个往下走一遍，有进行展再交流哈

**Comment by wzy1845** [comment]
> > > > 看了一下其他的问题，在一个里面作者给出了关于part_len的回答： L=32 for all the datasets and models. T=3 for UCF_C3D, T=4 for UCF_I3D, T=7 for Shanghaitech.
> > > 
> > > 
> > > 我也碰见了这个问题，但是我使用的就是上海科技大学的数据集，按照他默认的配置，也训练不出大于0.9的模型，不知道老哥这里调整了哪些参数，训练出来了吗
> > 
> > 
> > 额，到现在为止并没有得到大于0.9的结果。 然后之前以为SHT_I3D_AUC_0.9483.pth这个模型是阶段一的结果，但发现这个是最后阶段2的模型，所以0.94也就没有参考意义。
> > 我比较过我的0.879得到的伪标签和他的感觉差距还是挺大的。但是我还没有进行阶段2的训练，所以还不清楚这两个伪标签的差距。你有用自己训练的伪标签进行阶段2的训练么，结果如何？
> > 你的意思是你没有用他提供的这个处理过的特征集 ”SHT_I3D_RGB.h5“，是自己用上海科技的数据用I3D训练得到特征再进行阶段1的训练的么？
> > 参数吗，阶段1涉及的参数很少呀，感觉就四个吧，part_num,part_len,这两个涉及采样方法，topk，lambda_1这两个涉及loss。
> > 最近还有其他事，不是很有时间一直复现这个结果，之后要是有了进展，在交流。
> 
> 我复现出来的差不多也是0.87，正准备按照这个往下走一遍，有进行展再交流哈

你好！请问用0.9以下的模型往下走能达到文章中的结果吗？
