### ISSUE TITLE
about MIL.pth

### ISSUE THREAD

**Issue by Smallwhite999** [fjchange/MIST_VAD#30]
作者您好，感谢您非常优秀的代码，
我想请教一下在参数设置中的MIL.pth文件怎么没有啊？
parser.add_argument('--model_path',type=str,default='/jiachang/Weakly_Supervised_VAD/Datasets/MIL.pth')
这个.pth文件是要在第一步中生成还是在read.me中的连接下载啊？但是我看里面没有

**Comment by fjchange** [comment]
It is trained by yourself. You can also use our pseudo labels directly for stage2 training.
