### ISSUE TITLE
Feature Shape

### ISSUE THREAD

**Issue by Hepta-Col** [fjchange/MIST_VAD#34]
For each of the feature in 'SHT_I3D_RGB.h5' you provided, the size of the first dimension is not determined:
""
(47, 1024)
(16, 1024)
(27, 1024)
(21, 1024)
...
""
Could you tell me what this dimension means? Thanks!

**Comment by fjchange** [comment]
The given features are provided as the [T, C], which means clip nums and feature dims. And the videos they belong to are recorded in an external .txt file. Each of them is extracted from I3D. Every consecutive 16 frames for a clip. 

Hope it helps.
