### ISSUE TITLE
Vis

### ISSUE THREAD

**Issue by prolixiaoxiao** [fjchange/MIST_VAD#4]
For the Grad-cam, the stage-1 output feature is n*1024 and n scores after self.regressor(x), however the requirement of Grad-cam feature map is at least 3 dim, so if there is any ways to deal with the stage -1 visualization with grad-cam? Looking forward to your answers.

**Comment by fjchange** [comment]
If you wanna visualize the stage-1, you may need to save the pre-extracted feature maps (which cost too much memory space) OR you can merge the regressor with feature encoder to get a 3-d input online.
