### ISSUE TITLE
Question about make_h5.py

### ISSUE THREAD

**Issue by Jupiter-hzh** [fjchange/MIST_VAD#5]
tostring( ) is not supported in Python > 3.6, so I use tobytes( ) instead, but it looks like something wrong happened in frame. It has NULL so it can't work. Can you help me?
![image](https://user-images.githubusercontent.com/77839109/122185672-dc98aa00-cebf-11eb-9a4a-960b4d9f4929.png)

**Comment by luca-zanella-dvl** [comment]
Hi @Jupiter-hzh, as described in the [h5py documentation](https://docs.h5py.org/en/stable/high/group.html#h5py.Group.create_dataset), the `data` parameter in `create_dataset` should be a NumPy array. Therefore, I fixed this error by converting `tmp_frames`, which is a list, to a NumPy array before passing it to `create_dataset`. In any case, I would like to hear from the authors if this is the correct way to handle the problem.

**Comment by fjchange** [comment]
The target of using h5py is just reducing the indexing time in training stage. If you wanna to test it only, you can rewrite the dataset  to read videos directly.

**Comment by chuong98** [comment]
> Hi @Jupiter-hzh, as described in the [h5py documentation](https://docs.h5py.org/en/stable/high/group.html#h5py.Group.create_dataset), the `data` parameter in `create_dataset` should be a NumPy array. Therefore, I fixed this error by converting `tmp_frames`, which is a list, to a NumPy array before passing it to `create_dataset`. In any case, I would like to hear from the authors if this is the correct way to handle the problem.

Thanks. For anyone has the same error, here is the snipet:
```
            tmp_frames = np.asarray(tmp_frames)
            h.create_dataset(key,data=tmp_frames,chunks=True)
```

**Comment by fjchange** [comment]
I have updated the codes of this part, thanks @chuong98 @luca-zanella-dvl
