### ISSUE TITLE
Question about test.py! 

### ISSUE THREAD

**Issue by Jupiter-hzh** [fjchange/MIST_VAD#7]
Hi！
We're still trying to implement your code these days. . We have successfully obtained the H5 file of UCF_CRIME. But we are having trouble with `test.py`. Can you give me some help?
![image](https://user-images.githubusercontent.com/77839109/122671698-864aa480-d1fa-11eb-9cc8-8b448eeea21d.png)
We hope you success in your work!

**Comment by fjchange** [comment]
It seems a problem in the h5py file, make sure the key in h5py file the same as the indexing one.

ps. H5 file is not necessary for testing, you can directly read from the videos by modifying the ` dataset.py`
